import type { AppDefinition } from "@/types";

export const builtInApps: AppDefinition[] = [
  {
    id: "terminal",
    name: "Terminal",
    icon: "⌨️",
    description: "Command-line terminal with shell access",
    category: "dev",
    component: "Terminal",
    defaultWidth: 720,
    defaultHeight: 480,
    minWidth: 400,
    minHeight: 250,
    isBuiltIn: true,
  },
  {
    id: "files",
    name: "Files",
    icon: "📁",
    description: "File manager for your virtual filesystem",
    category: "system",
    component: "Files",
    defaultWidth: 800,
    defaultHeight: 560,
    minWidth: 500,
    minHeight: 350,
    isBuiltIn: true,
  },
  {
    id: "browser",
    name: "Browser",
    icon: "🌐",
    description: "Web browser with iframe embedding",
    category: "utility",
    component: "Browser",
    defaultWidth: 1024,
    defaultHeight: 700,
    minWidth: 600,
    minHeight: 400,
    isBuiltIn: true,
  },
  {
    id: "code-editor",
    name: "Code Editor",
    icon: "📝",
    description: "Code editor with syntax highlighting",
    category: "dev",
    component: "CodeEditor",
    defaultWidth: 900,
    defaultHeight: 650,
    minWidth: 500,
    minHeight: 350,
    isBuiltIn: true,
  },
  {
    id: "chat",
    name: "Chat",
    icon: "💬",
    description: "Peer-to-peer chat using WebRTC",
    category: "social",
    component: "Chat",
    defaultWidth: 700,
    defaultHeight: 550,
    minWidth: 400,
    minHeight: 300,
    isBuiltIn: true,
  },
  {
    id: "app-builder",
    name: "App Builder",
    icon: "🔧",
    description: "Build apps from HTML/CSS/JS",
    category: "dev",
    component: "AppBuilder",
    defaultWidth: 900,
    defaultHeight: 650,
    minWidth: 500,
    minHeight: 350,
    isBuiltIn: true,
  },
  {
    id: "settings",
    name: "Settings",
    icon: "⚙️",
    description: "System settings and preferences",
    category: "system",
    component: "Settings",
    defaultWidth: 750,
    defaultHeight: 580,
    minWidth: 500,
    minHeight: 400,
    isBuiltIn: true,
  },
  {
    id: "notepad",
    name: "Notepad",
    icon: "📋",
    description: "Simple text editor",
    category: "productivity",
    component: "Notepad",
    defaultWidth: 600,
    defaultHeight: 450,
    minWidth: 300,
    minHeight: 200,
    isBuiltIn: true,
  },
  {
    id: "calculator",
    name: "Calculator",
    icon: "🔢",
    description: "Scientific calculator",
    category: "utility",
    component: "Calculator",
    defaultWidth: 350,
    defaultHeight: 500,
    minWidth: 280,
    minHeight: 400,
    isBuiltIn: true,
  },
  {
    id: "app-gallery",
    name: "App Gallery",
    icon: "🏪",
    description: "Browse and install community apps",
    category: "system",
    component: "AppGallery",
    defaultWidth: 850,
    defaultHeight: 600,
    minWidth: 500,
    minHeight: 400,
    isBuiltIn: true,
  },
];
